<div class="row">
    <div class="col-md-4 col-md-offset-4">
      <form class="form-horizontal" role="form">
        <fieldset>

          <!-- Form Name -->
          <legend>Crea tu cuenta</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Nombre</label>
            <div class="col-sm-10">
              <input type="text" placeholder="nombre" class="form-control">
            </div>
          </div>

          
            <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Localidad </label>
            <div class="col-sm-10">
              <input type="text" placeholder="localidad" class="form-control">
            </div>
          </div>
          
          
          
          
          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Email</label>
            <div class="col-sm-10">
              <input type="text" placeholder="email" class="form-control">
            </div>
          </div>

          
           <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Clave</label>
            <div class="col-sm-10">
              <input type="password" placeholder="clave" class="form-control">
            </div>
          </div>
          
          
          
          
          
        
          <!-- Text input-->
<!--           <div class="form-group"> -->
<!--             <label class="col-sm-2 control-label" for="textinput">State</label> -->
<!--             <div class="col-sm-4"> -->
<!--               <input type="text" placeholder="State" class="form-control"> -->
<!--             </div> -->

<!--             <label class="col-sm-2 control-label" for="textinput">Postcode</label> -->
<!--             <div class="col-sm-4"> -->
<!--               <input type="text" placeholder="Post Code" class="form-control"> -->
<!--             </div> -->
<!--           </div> -->



         
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </div>
          </div>

        </fieldset>
      </form>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->