<!-- Contenido principal -->
<section class="content">



	<!-- Form Name -->

	<div class="box box-primary" style="padding: 10px">

		<form data-toggle="validator" class="form-horizontal" role="form"
			method="post">
			<fieldset>
				<legend>Crea tu cuenta</legend>


				<div class="box-body" style="background-color: transparent;">
					<div class="form-group">
						<label for="nombre" class="col-sm-4 control-label">Nombre</label>
						<div class="col-sm-4">
							<input type="text" placeholder="nombre" id='nombre' name='nombre'
								class="form-control" data-error="Por favor, Ingrese su Nombre"
								required>
						</div>
						<div class="help-block with-errors"></div>
					</div>


					<div class="form-group">
						<label for="telefono" class="col-sm-4 control-label">Telefono</label>
						<div class="col-sm-4">
							<input type="text" pattern="^([0-9])+$" data-minlength="6"
								maxlength="10" placeholder="telefono" id='telefono'
								name='telefono' class="form-control"
								data-error="Por favor, Ingrese un telefono valido" required>
						</div>
						<div class="help-block with-errors"></div>
					</div>



					<div class="form-group">
						<label for="email" class="col-sm-4 control-label">Email</label>
						<div class="col-sm-4">
							<input type="email" placeholder="email" id='email' name='email'
								class="form-control"
								data-error="Por favor, Ingrese un email valido" required>
						</div>
						<div class="help-block with-errors"></div>
					</div>
					
					
					<div class="form-group">
						<label for="clave" class="col-sm-4 control-label">Clave</label>
						<div class="col-sm-4">
							<input type="password" data-minlength="6" placeholder="clave" id='clave' name='clave'
								class="form-control"
								data-error="Por favor, Ingrese una clave mayor a 5 digitos" required>
						</div>
						<div class="help-block with-errors"></div>
					</div>
					


				</div> <!-- / transparent -->

				<div class="box-footer">
					<div class="form-group">
						<label class="col-sm-4 control-label">&nbsp;</label>
						<div class="col-sm-4" style="text-align: center">

							<button type="submit" class="btn btn-primary  ">
								<span class="glyphicon glyphicon-floppy-saved"></span> Guardar
							</button>
						</div>
					</div>

				</div>



			</fieldset>
		</form>
		 <?php if($this->existe_cuenta){ ?>
    <div class="alert alert-danger">Ya exite una cuenta con este email <?php echo $this->existe_cuenta ?> </div>
    <?php } ?>
	</div>
	<!-- /.box-body -->




</section>



















