<div class="row">
    <div class="col-md-4 col-md-offset-4">
      <form data-toggle="validator" class="form-horizontal" role="form" method="post">
        <fieldset>

          <!-- Form Name -->
          <legend>Crea tu cuenta</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Nombre</label>
            <div class="col-sm-10">
              <input type="text" placeholder="nombre" id='nombre' name='nombre' class="form-control" required>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Telefono</label>
            <div class="col-sm-10">
              <input type="tel"  pattern="^([0-9])+$"  data-minlength="6"  maxlength="10" placeholder="telefono" id='telefono' name='telefono' class="form-control" 
              data-error="Por favor, Ingrese su numero telefonico"
              required>
                 
            </div>
             <div class="help-block with-errors"></div>
          </div>
          
          
          
          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="email">Email</label>
            <div class="col-sm-10">
              <input type="email" placeholder="email" id='email' name='email' class="form-control"
              data-error="Por favor, Ingrese un email valido"
               required>
                
            </div>
            <div class="help-block with-errors"></div>
          </div>

          
           <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Clave</label>
            <div class="col-sm-10">
              <input type="password" data-minlength="6" placeholder="clave" id='clave' name='clave'
                 class="form-control" data-error="Por favor, Ingrese mas de 6 caracteres" required>
            </div>
            <div class="help-block with-errors"></div>
          </div>
          
          
          
          
          
        
          <!-- Text input-->
<!--           <div class="form-group"> -->
<!--             <label class="col-sm-2 control-label" for="textinput">State</label> -->
<!--             <div class="col-sm-4"> -->
<!--               <input type="text" placeholder="State" class="form-control"> -->
<!--             </div> -->

<!--             <label class="col-sm-2 control-label" for="textinput">Postcode</label> -->
<!--             <div class="col-sm-4"> -->
<!--               <input type="text" placeholder="Post Code" class="form-control"> -->
<!--             </div> -->
<!--           </div> -->



         
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </div>
          </div>

        </fieldset>
      </form>
      <?php if($this->existe_cuenta){ ?>
    <div class="alert alert-danger">Ya exite una cuenta con este email <?php echo $this->existe_cuenta ?> </div>
    <?php } ?>
    </div><!-- /.col-lg-12 -->
    
</div><!-- /.row -->