  
 <style>


.ui-autocomplete {
	background-color: white;
	
	border: 1px solid #cfcfcf;
	list-style-type: none;
	padding-left: 0px;
}
</style>
 
 
<script type="text/javascript">

$(document).ready(function(){
   alert("hola mundo");



});


</script>

 
 
   
  <div style="width: 100%">
   <form>
    <label>Address: </label><input id="address" class="span6" type="text" />
    <div id="map_canvas" style="width:100%; height:500px;"></div><br/>
    <label>latitude: </label><input id="latitude" class="span6" type="text"/><br/>
    <label>longitude: </label><input id="longitude" class="span6" type="text"/>
  </form>
 </div>
















