
<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    <h1>
        Formulario de Prueba
        <small id="subtitle_header">Subtitulo</small>
    </h1>
</section>



<!-- Contenido principal -->
<section class="content">
    
        <div class="box box-primary" style="padding: 10px">
            
<!--            <div class="box-header">
                <h3 class="box-title">Titulo del formulario</h3>
            </div> /.box-header -->
            
            
            <form class="form-horizontal" role="form">
                <div class="box-body" style="background-color: transparent;">
                     <div class="form-group">
                       <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
                       <div class="col-sm-4">
                         <input type="email" class="form-control" id="inputEmail3" placeholder="Email">                         
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password222</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password444</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
<!--                     <div class="form-group">
                       <div class="col-sm-offset-2 col-sm-10">
                         <div class="checkbox">
                           <label>
                             <input type="checkbox"> Remember me
                           </label>
                         </div>
                       </div>
                     </div>
                     <div class="form-group">
                       <div class="col-sm-offset-2 col-sm-10">
                         <button type="submit" class="btn btn-default">Sign in</button>
                       </div>
                     </div>-->
                 </div>

                <div class="box-footer" >
                     <div class="form-group">
                       <label for="inputEmail3" class="col-sm-4 control-label">&nbsp;</label>
                       <div class="col-sm-4" style="text-align: right">
                         <button type="submit" class="btn btn-default">Cancel</button>                        
                         <button type="submit" class="btn btn-primary">Submit</button>                        
                       </div>
                     </div>
                     
                 </div>
             </form>
            
         </div><!-- /.box-body -->
         
            
        </div><!-- /.row -->
       
</section>

