<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    <h1>
        Listados Usuario 
        <small id="subtitle_header">Inicio</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add User</a>                  
        </li>
        <li>
             <a href="<?php echo $this->url('login', array('action'=>'autenticar'));?>">login</a>
        </li>
    </ol>
</section>

<!-- Contenido principal -->
<section id="main_content" class="content">
    <div class="row">

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
        
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Users</h3>
                <div class="box-tools">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="#">&laquo;</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body no-padding">
                <table class="table">
                    <tr>
                        <th style="width: 10px">Id</th>
                        <th>Full name</th>
                        <th>Action</th>
                    </tr>
                    <?php foreach($users as $user): ?>
                    <tr>
                        <td><?php echo $user['id']; ?></td>
                        <td><?php echo $user['fullName']; ?></td>
                        <td><a
                            href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user['id']));?>">Edit</a>
                            | <a
                            href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user['id']));?>">Delete</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->

    </div><!-- /.col -->
            
    </div>
</section>


    
