
<style>
#footer {
/*    background-color: #f5f5f5;
    border-top: 1px solid #dddddd;
    box-shadow: 0 1px 1px #fff inset;*/
    
    
  background-color: #0A83FF;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.45) 100%) repeat scroll 0 0 #0A83FF;
  box-shadow: 0 0 7px rgba(0, 0, 0, 0.7);
  color: #fff;
}
</style>
<!-- AGE FOOTER -->
<div id="footer" class="page-footer" >
        <div class="row">
                <div class="col-xs-12 col-sm-12">
                        <p style="text-align: center; font-weight: 600; padding: 5px">SmartAdmin WebApp © 2013-2014</p>
                </div>
        </div>
        <!-- end row -->
</div>
<!-- END FOOTER -->
