
<!-- AGE FOOTER -->
<header class="header"  >
<div style="background-color: #0732a2;height: 40px" >
        <div class="row" >
                <div class="col-xs-12 col-sm-12" >
                        <p style="color: #fff; text-align: center"><a style="height: 40px" href="<?php echo $this->url('home') ?>" class="logo">UGKamari</a></p>
                </div>
        </div>
        <!-- end row -->
</div>
</header>