

<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/orlando.jpg" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Hola Orlando</p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Texto a buscar..."/>
                <span class="input-group-btn">
                    <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="active">
                <a href="index.html" onclick="setTitle('Lugares y Eventos')">
                    <i class="fa fa-dashboard"></i> <span>Eventos</span>
                </a>
            </li>
            <li>
                <a href="pages/widgets.html" onclick="setTitle('Transporte Seguro')">
                    <i class="fa fa-th"></i> <span>Transporte</span> 
                    <!--<small class="badge pull-right bg-green">new</small>-->
                </a>
            </li>
            <li class="treeview">
                <a href="#" onclick="setTitle('Empresas o negocios')">
                    <i class="fa fa-bar-chart-o"></i>
                    <span>Empresas</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>"><i class="fa fa-angle-double-right"></i>Tiendas</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>" ><i class="fa fa-angle-double-right"></i> Comer</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>"><i class="fa fa-angle-double-right"></i> Café y bares</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>" ><i class="fa fa-angle-double-right"></i> Cultura</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>" ><i class="fa fa-angle-double-right"></i> Dormir</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>" ><i class="fa fa-angle-double-right"></i> Aire Libre</a></li>
                    <li><a href="<?php echo $this->url('user', array('action'=>'negocio'));?>" ><i class="fa fa-angle-double-right"></i> Todos</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#" onclick="setTitle('Productos')">
                    <i class="fa fa-laptop"></i>
                    <span>Comerciantes</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Alimentación');" ><i class="fa fa-angle-double-right"></i> Alimentación</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Calzado y piel');" ><i class="fa fa-angle-double-right"></i> Calzado y piel</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Complementos y regalos');" ><i class="fa fa-angle-double-right"></i> Complementos y regalos</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Decoración');" ><i class="fa fa-angle-double-right"></i> Decoración</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Deportes');" ><i class="fa fa-angle-double-right"></i> Deportes</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Electrodomésticos');" ><i class="fa fa-angle-double-right"></i> Electrodomésticos</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Floristerías');" ><i class="fa fa-angle-double-right"></i> Floristerías</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Fotografía');" ><i class="fa fa-angle-double-right"></i> Fotografía</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Informática y Electrónica');" ><i class="fa fa-angle-double-right"></i> Informática y Electrónica</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Joyerías');" ><i class="fa fa-angle-double-right"></i> Joyerías</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Librerías/Salas de arte');" ><i class="fa fa-angle-double-right"></i> Librerías/Salas de arte</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Moda');" ><i class="fa fa-angle-double-right"></i> Moda</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Muebles');" ><i class="fa fa-angle-double-right"></i> Muebles</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Ocio y tiempo libre');" ><i class="fa fa-angle-double-right"></i> Ocio y tiempo libre</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Opticas');" ><i class="fa fa-angle-double-right"></i> Opticas</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Peluquerías');" ><i class="fa fa-angle-double-right"></i> Peluquerías</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Perfumerías');" ><i class="fa fa-angle-double-right"></i> Perfumerías</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Salud y belleza');" ><i class="fa fa-angle-double-right"></i> Salud y belleza</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Servicios profesionales');" ><i class="fa fa-angle-double-right"></i> Servicios profesionales</a></li>
                </ul>
            </li>
            
             <li class="treeview">
                <a href="#" onclick="setTitle('Productos')">
                    <i class="fa fa-laptop"></i>
                    <span>Mis Datos</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?php echo $this->url('negocio', array('action'=>'add'));?>"><i class="fa fa-angle-double-right"></i> Negocios</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Calzado y piel');" ><i class="fa fa-angle-double-right"></i>Productos</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Complementos y regalos');" ><i class="fa fa-angle-double-right"></i> Mensajes</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Decoración');" ><i class="fa fa-angle-double-right"></i> Datos Personales</a></li>
                    <li><a href="#" onclick="loadMain(event , 'pages/productos.php','Decoración');" ><i class="fa fa-angle-double-right"></i> Modificar Cuenta</a></li>
                
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>