<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Users</h3>
			</div>
			<div class="panel-body">
				<a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add
					User</a>
                 <a href="<?php echo $this->url('login', array('action'=>'autenticar'));?>">login
				</a>
					
                <?php if (isset($users)) : ?>
                <table class="table">
					<thead>
						<tr>
							<th>Id</th>
							<th>Full name</th>
							<th></th>
						</tr>
					</thead>
                <?php foreach($users as $user): ?>
                    <tbody>
						<tr>
							<td><?php echo $user['id']; ?></td>
							<td><?php echo $user['fullName']; ?></td>
							<td><a
								href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user['id']));?>">Edit</a>
								| <a
								href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user['id']));?>">Delete</a>
							</td>
						</tr>
					</tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
		</div>
	</div>
</div>
