
<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    <h1>
        Empresas o negocios
        <small id="subtitle_header">Detalles Propietario</small>
    </h1>
</section>


<!-- Contenido principal -->
<section id="main_content" class="content">
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
                <div id="map1" class="map">
                </div>
        </div>
    </div>
    
    <div class="row" style="padding-left: 20px ">
         <!--col-xs-12 col-sm-12 col-md-12 col-lg-12-->
        <div class="col-xs-1 col-sm-2 col-md-2 col-lg-1" >                            
            <img src="<?php echo $this->basePath(); ?>/images/categoria/coffeeshop_bg.png" alt=""/>
        </div>
         <div class="col-xs-11 col-sm-10 col-md-10 col-lg-11"> 
            <h1>Bootstrappage Restaurant</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy </p>     
            
            <div class="text-center">
                    <a href="#"><span class="glyphicon glyphicon-plus"></span> Full Story</a>
                    <a href="#"><span class="glyphicon glyphicon-comment"></span> 12 Comments</a>
                    <a href="#"><span class="glyphicon glyphicon-share"></span> 11 Shares</a>
            </div>
        </div>
    </div>
    
    
    <div class="list-group">
                <a href="#" class="list-group-item">
                    <div class="media col-md-3">
                        <figure class="pull-left">
                            <i class="fa fa-cloud-upload blogicon"></i>
                        </figure>
                    </div>
                    <div class="col-md-6">
                        <h4 class="list-group-item-heading">Blog Title</h4>
                        <p class="list-group-item-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec sem molestie, tempor libero eu, placerat purus. 
                            Donec eget iaculis elit. Nam eget consectetur quam. Nam viverra ornare diam. In a ornare diam. 
                            Quisque vestibulum nulla nec facilisis malesuada. 
                            Proin at lobortis risus. Vivamus tristique eros vel cursus malesuada. 
                            Vivamus volutpat, sem nec venenatis iaculis, metus felis interdum mi, et venenatis felis mi at eros. 
                            Phasellus vel massa nisi. Fusce ut vehicula nunc. Nullam egestas eros risus, eu fringilla odio lacinia ac. 
                            Fusce placerat a dolor et tincidunt. 
                            Pellentesque tristique nunc et nibh scelerisque euismod. 
                            Sed tristique arcu sit amet nulla auctor ultricies.
                        </p>
                    </div>
                    <div class="col-md-3 text-center">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="ratetext">Rate it</div>
                                <i class="fa fa-thumbs-o-up votes"></i><i class="fa fa-thumbs-o-down votes"></i>
                                <div class="stars"></div>
                                <h2>464  <small>Clicks</small></h2>
                                <div id="rate1"></div>
                            </div>
                        </div>
                    </div>
                </a>
    </div>
         
         
    
    
   
      <div class="row">
            <div class="col-xs-12">
                <h2>Article Title</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. 
                    Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis 
                    dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. 
                    Aliquam in felis sit amet augue.
                </p>
                <div class="text-center">
                    <a href="#"><span class="glyphicon glyphicon-plus"></span> Full Story</a>
                    <a href="#"><span class="glyphicon glyphicon-comment"></span> 12 Comments</a>
                    <a href="#"><span class="glyphicon glyphicon-share"></span> 11 Shares</a>
                </div>
            </div>
        </div>
    
    
    <div class="mainTitle"> 
       
        
    </div>
    

<!-- Three columns of text below the carousel -->
   <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
         <img src="AdminLTE-master/img/producto1.jpg" alt=""/>     
      </div>
      <div class="caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p>
      </div>
       <p style="text-align: center">
          <a class="btn btn-default" role="button" href="#" style="background-color: #7db641;border-color: #7db641;color: #000;">£ 2.2 Add to cart »</a>
      </p>
   </div>
   <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
          <img src="AdminLTE-master/img/producto2.jpg" alt=""/>
      </div>
      <div class="caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p>
      </div>
      <p style="text-align: center">
          <a class="btn btn-default" role="button" href="#" style="background-color: #7db641;border-color: #7db641;color: #000;">£ 2.2 Add to cart »</a>
      </p>
   </div>
   <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
          <img src="AdminLTE-master/img/producto3.jpg" alt=""/>
      </div>
      <div class="caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p>
      </div>
       <p style="text-align: center">
          <a class="btn btn-default" role="button" href="#" style="background-color: #7db641;border-color: #7db641;color: #000;">£ 2.2 Add to cart »</a>
      </p>
   </div>
   <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
           <img src="http://placehold.it/750x450" alt="">
      </div>
      <div class="caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p>
      </div>
   </div>

</div>
    
    
    
   
   <div class="row">
        <div class="col-xs-12 col-sm-6 col-lg-4">
            <div class="box">
                <div class="icon">
                    <div class="image"><span class="glyphicon glyphicon-list-alt btn-lg white"></span></div>
                    <div class="info">
                        <h3 class="title">Tasks</h3>
                        <p>
                            12 pending tasks awaiting approval and review.
                        </p>
                        <div class="more">
                            <a href="#" title="Title Link"><i class="fa fa-plus"></i> Details
                            </a>
                        </div>
                    </div>
                </div>
                <div class="space"></div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-lg-4">
            <div class="box">
                <div class="icon">
                    <div class="image"><span class="glyphicon glyphicon-envelope btn-lg white"></span></div>
                    <div class="info">
                        <h3 class="title">Messages</h3>
                        <p>
                            7 new messages over the past 24 hours. 
                        </p>
                        <div class="more">
                            <a href="#" title="Title Link"><i class="fa fa-plus"></i> Details
                            </a>
                        </div>
                    </div>
                </div>
                <div class="space"></div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-lg-4">
            <div class="box">
                <div class="icon">
                    <div class="image"><span class="glyphicon glyphicon-volume-up btn-lg white"></span></div>
                    <div class="info">
                        <h3 class="title">Mentions</h3>
                        <p>
                            47 new mentions for the past week.
                        </p>
                        <div class="more">
                            <a href="#" title="Title Link"><i class="fa fa-plus"></i> Details
                            </a>
                        </div>
                    </div>
                </div>
                <div class="space"></div>
            </div>
        </div>
    </div>      
    
</section>

<style>
.mainTitle {
    background: none repeat scroll 0 0 #fafafa;
    border-top: 1px solid #ff8500;
    box-shadow: 0 0 24px #d5d5d5;
    color: #0c0c0c;
    padding: 4px 0;
    text-align: center;
}
</style>

<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false"></script>
<script type="text/javascript">
    jQuery(function ($) {
        function init_map1() {
            var myLocation = new google.maps.LatLng(51.508742,-0.120850);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map1"),
                mapOptions);
            marker.setMap(map);
        }
        
        init_map1();
       
    });
</script>

<style>
    .gmnoprint img {
        max-width: none; 
    }

    .map {
        min-width: 300px;
        min-height:200px;
        width:100%;
    }

    img {
        max-width: 110%;
        height: auto;
    }

    .clearfix {
        clear: both;
    }

    .rowcolor {
        background-color: #CCCCCC;
    }

    .padall {
        padding: 10px;
    }

    .padbig {
        padding: 20px;
    }

    .icon {
        font-size: 23px;
        color: #197BB5;
    }
</style>




<style>
.white {
    color: white;
}

.btn-lg {
    font-size: 38px;
    line-height: 1.33;
    border-radius: 6px;
}

.box > .icon {
    text-align: center;
    position: relative;
}

.box > .icon > .image {
    position: relative;
    z-index: 2;
    margin: auto;
    width: 88px;
    height: 88px;
    border: 7px solid white;
    line-height: 88px;
    border-radius: 50%;
    background: #63B76C;
    vertical-align: middle;
}

.box > .icon:hover > .image {
    border: 4px solid black;
}

.box > .icon > .image > i {
    font-size: 40px !important;
    color: #fff !important;
}

.box > .icon:hover > .image > i {
    color: white !important;
}

.box > .icon > .info {
    margin-top: -24px;
    background: rgba(0, 0, 0, 0.04);
    border: 1px solid #e0e0e0;
    padding: 15px 0 10px 0;
}

    .box > .icon > .info > h3.title {
        color: #222;
        font-weight: 500;
    }

    .box > .icon > .info > p {
        color: #666;
        line-height: 1.5em;
        margin: 20px;
    }

.box > .icon:hover > .info > h3.title, .box > .icon:hover > .info > p, .box > .icon:hover > .info > .more > a {
    color: #222;
}

.box > .icon > .info > .more a {
    color: #222;
    line-height: 12px;
    text-transform: uppercase;
    text-decoration: none;
}

.box > .icon:hover > .info > .more > a {
    color: #000;
    padding: 6px 8px;
    border-bottom: 4px solid black;
}

.box .space {
    height: 30px;
}
</style>








<div class="container">
    <div class="row">
        <div class="well">
            <h1 class="text-center">Today's Blogposts</h1>
            <div class="list-group">
                
                <a href="#" class="list-group-item">
                    <div class="media col-md-2">
                        <figure class="pull-left">
                             <img src="<?php echo $this->basePath(); ?>/images/categoria/coffeeshop_bg.png" alt=""/>
                        </figure>
                    </div>
                    <div class="col-md-10">
                        <h4 class="list-group-item-heading">Blog Title</h4>
                        <p class="list-group-item-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec sem molestie, tempor 
                        </p>   
                    </div>
                </a>
                
            </div>
        </div>
    </div>
</div>
<style>
.blogicon {
    font-size: 217px;
    color:#5CB85C;
}

.ratetext {
    font-size: 37px;
    text-decoration: underline;
    padding-bottom: 10px;
}

.votes {
    font-size: 47px;
    padding-right: 20px;
    color:#197BB5;
}

a.list-group-item {
    height: auto;
    min-height: 100px;
}

a.list-group-item:hover, a.list-group-item:focus {
    border-left:10px solid #5CB85C;
    border-right:10px solid #5CB85C;
}

a.list-group-item {
    border-left:10px solid transparent;
    border-right:10px solid transparent;
}
</style>