
<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    
    <div class="pageicon">
        <span class="glyphicon glyphicon-pencil"></span>
    </div>
    <div class="pagetitle">
        <h5>Forms</h5>
        <h1>Form Styles</h1>
    </div>
</section>



<!-- Contenido principal -->
<section class="content">
    
    <div class="box widgetcontent_blue">
        <!--style="background: #000"-->
            <div class="box-header" >
                <h4 class="box-title">Titulo del formulario</h4>
            </div> 
            
            
            <form class="form-horizontal" role="form">
                <div class="box-body" style="background-color: transparent;">
                     <div class="form-group">
                       <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
                       <div class="col-sm-4">
                         <input type="email" class="form-control" id="inputEmail3" placeholder="Email">                         
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password222</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
                     <div class="form-group">
                       <label for="inputPassword3" class="col-sm-4 control-label">Password444</label>
                       <div class="col-sm-4">
                         <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                       </div>
                     </div>
<!--                     <div class="form-group">
                       <div class="col-sm-offset-2 col-sm-10">
                         <div class="checkbox">
                           <label>
                             <input type="checkbox"> Remember me
                           </label>
                         </div>
                       </div>
                     </div>
                     <div class="form-group">
                       <div class="col-sm-offset-2 col-sm-10">
                         <button type="submit" class="btn btn-default">Sign in</button>
                       </div>
                     </div>-->
                 </div>

                <div class="box-footer" >
                     <div class="form-group">
                       <label for="inputEmail3" class="col-sm-4 control-label">&nbsp;</label>
                       <div class="col-sm-4" style="text-align: right">
                         <button type="submit" class="btn btn-default">Cancel</button>                        
                         <button type="submit" class="btn btn-primary">Submit</button>                        
                       </div>
                     </div>
                     
                 </div>
             </form>
            
    </div><!-- /.box-body -->
          
       
</section>

