
<style>
.vcenter {
    display: inline-block;
    vertical-align: middle;
    float: none;
}

</style>


<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    
    <div class="pageicon">
        <span class="fa fa-th-large"></span>
    </div>
    <div class="pagetitle">
        <h5>&nbsp;</h5>
        <h1>Menu Central</h1>
    </div>
</section>



<!-- Contenido principal -->
<section id="main_content" class="content">
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="padding_sm col-lg-3 col-md-3 col-sm-4 col-xs-12">
    	<div id="tile1" class="tile">
                <!--<div class="carousel slide" data-ride="carousel">-->
                    <!-- Wrapper for slides -->
                    <!--<div class="carousel-inner">-->
                      <div class="item active">  
                            <div class="small-box bg-aqua" >
                                <div class="inner" style="padding-top: 24px">
                                    <h3> 150 </h3>
                                    <p> Empresa o Negocio </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                                <a class="small-box-footer" href="#" style="margin-top: 50px">
                                    More info<i class="fa fa-arrow-circle-right"></i>
                                </a>
                            </div>
                      </div>
                      <!--<div class="item">
                         <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/negocio.jpg" class="img-responsive"/>
                      </div>
                    </div>-->
               <!--</div>-->
    	</div>
    </div>
    <div class="padding_sm col-lg-3 col-md-3  col-sm-4 col-xs-12">
        <div id="tile2" class="tile">
            <!--<div class="carousel slide" data-ride="carousel">-->
             <!-- Wrapper for slides -->
             <!--<div class="carousel-inner">-->
               <div class="item active">
                    <div class="small-box bg-green" style="height: 160px">
                        <div class="inner" style="padding-top: 24px">
                            <h3> 150 </h3>
                            <p> Lugares y Eventos </p>
                        </div>
                        <div class="icon">
                            <i class="glyphicon glyphicon-pushpin"></i>
                        </div>
                        <a class="small-box-footer" href="#" style="margin-top: 50px">
                            More info<i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
               </div>
               <!--<div class="item">
                 <img src="http://handsontek.net/demoimages/tiles/hot2.png" class="img-responsive"/>
               </div>
               <div class="item">
                 <img src="http://handsontek.net/demoimages/tiles/hot3.png" class="img-responsive"/>
               </div>
             </div>
           </div>-->
        </div>
    </div>
    <div class="padding_sm col-lg-3 col-md-3  col-sm-4 col-xs-12">
        <div id="tile3" class="tile">
    	 
        <!--<div class="carousel slide" data-ride="carousel">-->
          <!-- Wrapper for slides -->
          <!--<div class="carousel-inner">-->
            <div class="item active">
                <div class="small-box bg-light-blue" style="height: 160px">
                    <div class="inner" style="padding-top: 24px">
                        <h3> 150 </h3>
                        <p> Transportes </p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-dashboard"></i>
                    </div>
                    <a class="small-box-footer" href="#" style="margin-top: 50px">
                        More info<i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!--<div class="item">
               <img src="http://handsontek.net/demoimages/tiles/weather.png" class="img-responsive"/>
            </div>-->
<!--            </div>
        </div>-->
        </div>
    </div>	
    
    
    <div class="padding_md padding_sm col-lg-3 col-md-3 col-sm-4  col-xs-12">
        <div id="tile5" class="tile">
            <!--<div class="carousel slide" data-ride="carousel">-->
             <!-- Wrapper for slides -->
             <!--<div class="carousel-inner">-->
                <div class="item active">
                    <div class="small-box bg-teal" style="height: 160px">
                        <div class="inner" style="padding-top: 24px">
                            <h3> 150 </h3>
                            <p> Productos </p>
                        </div>
                        <div class="icon">
                            <i class="glyphicon glyphicon-shopping-cart"></i>
                        </div>
                        <a class="small-box-footer" href="#" style="margin-top: 50px">
                            More info<i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>
                <div class="item">
                 <!--<img src="http://handsontek.net/demoimages/tiles/neews2.png" class="img-responsive"/>-->
               </div>
             <!--</div>-->
           <!--</div>-->
        </div>
    </div>
    <div class="padding_lg padding_md padding_sm col-lg-3 col-md-3 col-sm-4  col-xs-12">
        <div id="tile6" class="tile">
            <!--<div class="carousel slide" data-ride="carousel">-->
             <!-- Wrapper for slides -->
             <!--<div class="carousel-inner">-->
               <div class="item active">
                    <div class="small-box bg-blue" style="height: 160px">
                        <div class="inner" style="padding-top: 24px">
                            <h3> 150 </h3>
                            <p> Eventos </p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <a class="small-box-footer" href="#" style="margin-top: 50px">
                            More info<i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
               </div>
               <!--<div class="item">
                 <img src="http://handsontek.net/demoimages/tiles/skype2.png" class="img-responsive"/>
               </div>-->
             <!--</div>-->
           <!--</div>-->
        </div>
    </div>
</div>    



<!--<div class="row">
    <div class="col-lg-3 col-xs-6">
         small box 
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    150
                </h3>
                <p>
                    New Orders
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div> ./col 
    <div class="col-lg-3 col-xs-6">
         small box 
        <div class="small-box bg-green">
            <div class="inner">
                <h3>
                    53<sup style="font-size: 20px">%</sup>
                </h3>
                <p>
                    Bounce Rate
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div> ./col 
    <div class="col-lg-3 col-xs-6">
         small box 
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>
                    44
                </h3>
                <p>
                    User Registrations
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div> ./col 
    
    <div class="col-lg-3 col-xs-6">
         small box 
        <div class="small-box bg-red">
            <div class="inner">
                <h3>
                    65
                </h3>
                <p>
                    Unique Visitors
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div> ./col 
    
    <div class="col-lg-3 col-xs-6">
         small box 
        <div class="small-box bg-red">
            <div class="inner">
                <h3>
                    65
                </h3>
                <p>
                    Unique Visitors
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div> ./col 
    
</div> /.row -->


    
<!--<div class="row">
	<div class="col-sm-4 col-xs-8">
		<div id="tile7" class="tile">
    	 
        <div class="carousel slide" data-ride="carousel">
           Wrapper for slides 
          <div class="carousel-inner">
            <div class="item active">
              <img src="http://handsontek.net/demoimages/tiles/gallery.png" class="img-responsive"/>
            </div>
            <div class="item">
              <img src="http://handsontek.net/demoimages/tiles/gallery2.png" class="img-responsive"/>
            </div>
            <div class="item">
              <img src="http://handsontek.net/demoimages/tiles/gallery3.png" class="img-responsive"/>
            </div>
          </div>
        </div>
         
		</div>
	</div>
	<div class="col-sm-2 col-xs-4">
		<div id="tile8" class="tile">
    	 
         <div class="carousel slide" data-ride="carousel">
           Wrapper for slides 
          <div class="carousel-inner">
            <div class="item active">
               <img src="http://handsontek.net/demoimages/tiles/music.png" class="img-responsive"/>
            </div>
            <div class="item">
               <img src="http://handsontek.net/demoimages/tiles/music2.png" class="img-responsive"/>
            </div>
            </div>
         </div>
         
		</div>
	</div>
	<div class="col-sm-2 col-xs-4">
		<div id="tile9" class="tile">
    	 
          <div class="carousel slide" data-ride="carousel">
           Wrapper for slides 
          <div class="carousel-inner">
            <div class="item active">
              <img src="http://handsontek.net/demoimages/tiles/calendar.png" class="img-responsive"/>
            </div>
            <div class="item">
              <img src="http://handsontek.net/demoimages/tiles/calendar2.png" class="img-responsive"/>
            </div>
          </div>
        </div>
         
		</div>
	</div>
	<div class="col-sm-4 col-xs-8">
		<div id="tile10" class="tile">
    	 
           <div class="carousel slide" data-ride="carousel">
           Wrapper for slides 
          <div class="carousel-inner">
            <div class="item active">
              <h3 class="tilecaption"><i class="fa fa-child fa-4x"></i></h3>
            </div>
            <div class="item">
              <h3 class="tilecaption">Customize your tiles</h3>
            </div>
            <div class="item">
              <h3 class="tilecaption">Text, Icons, Images</h3>
            </div>
            <div class="item">
              <h3 class="tilecaption">Combine them and create your metro style</h3>
            </div>
          
          </div>
        </div>
         
		</div>
	</div>
  
</div>-->

    
</section>


