
<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    <h1>
        Empresas o negocios
        <small id="subtitle_header">Tiendas</small>
    </h1>
</section>

<style>    
.address {
    color: #aeb4b6 !important;
    font-family: inherit;
    font-weight: bold;
    line-height: 21px;
    margin: 0px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;    
}
.venueScore {
   border-radius: 34px;
    color: #fff;
    float: left;
    font-size: 13px;
    line-height: 34px;
    margin-right: 10px;
    min-width: 34px;
    padding: 0;text-align: center;
    text-shadow: none;
    width: auto;
    background: none repeat scroll 0 0 #00b551; 
} 
.box-body ,.thumbnail  { background: none repeat scroll 0 0 #f3f5fb; }
.box-body .thumbnail  {border:none;}
thumbnail, .thumbnail img{
   height:175px;
} 
.specialInfo { background: none repeat scroll 0 0 #fff4d8  !important; }
.box-header { backgro-und: none repeat scroll 0 0 #f3f5fb; }


</style>
<!-- Contenido principal -->
<section id="main_content" class="content">

<div class="row" style="background-color: #F5F5F5">
    <div class="col-md-6 col-sm-6  col-xs-12">  
            <form class="navbar-form" role="search">
                <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                        <div class="input-group-btn">
                            <button style="padding: 9px 12px;" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                </div>
            </form>
    </div>
    <div class="col-md-6 col-sm-6  col-xs-12" style="padding: 10px"> 
       <div class="btn-toolbar" role="toolbar">
           <div class="btn-group">
          
               <button id="btn_oferta" class="btn btn-default btn" onclick="$('#btn_oferta').removeClass('btn-default btn').addClass('bg-yellow btn' );">
                    <i class="glyphicon glyphicon-star"></i>&nbsp;
                    <span>Oferta</span>  
                </button>
                
           </div>
           <div class="btn-group">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                Ubicacion
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Guayas</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Quito</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Machala</a></li>
                <li role="presentation" class="divider"></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Mas opciones</a></li>
              </ul>
            </div>
           </div>
          
        </div>
    </div>
</div>  
<br>
    
    
    
        <div class="row">
            <div class="col-lg-3 col-xs-12 col-sm-6  col-md-4 "> 
                <!-- Default box -->
                <div class="box box-primary">
                    <div class="box-header" style="background: none repeat scroll 0 0 #f3f5fb;">
                        <h3 class="box-title" style="font-weight: bold; line-height: 21px;"> 
                            <a style="color: #2d5be3;" href="<?php echo $this->url('user', array('action'=>'detalles'));?>">Admin, Inc.</a>
                        </h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #f3f5fb;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body">
                        <a href="#" class="thumbnail">
                             <img  src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6 col-md-4">
                <!-- Default box -->
                <div class="box box-primary">
                    <div class="box-header" style="background: none repeat scroll 0 0 #f3f5fb;">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #f3f5fb;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body">
                        <a href="#" class="thumbnail">
                             <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6 col-md-4">
                <!-- Default box -->
                <div class="box box-primary">
                    <div class="box-header" style="background: none repeat scroll 0 0 #f3f5fb;">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #f3f5fb;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body">
                        <a href="#" class="thumbnail">
                             <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6 col-md-4">
                <!-- Default box -->
                <div class="box box-primary">
                    <div class="box-header" style="background: none repeat scroll 0 0 #f3f5fb;">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #f3f5fb;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body">
                        <a href="#" class="thumbnail">
                             <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->

        
        
        <div class="row">
            <div class="col-lg-3 col-xs-12 col-sm-6  col-md-4 ">
                <!-- Default box -->
                <div class="box box-warning">
                    <div class="box-header specialInfo">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore bg-yellow"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #fff4d8;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body specialInfo">
                        <a href="#" class="thumbnail specialInfo">
                             <img  src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6  col-md-4 ">
                <!-- Default box -->
                <div class="box box-warning">
                    <div class="box-header specialInfo">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right" style="padding-top: 0;padding-right: 0">                                                       
                            <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/special-banner1.png" alt=""/>
                            
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #fff4d8;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body specialInfo">
                        <a href="#" class="thumbnail specialInfo">
                             <img  src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6  col-md-4 ">
                <!-- Default box -->
                <div class="box box-warning">
                    <div class="box-header specialInfo">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore bg-yellow"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #fff4d8;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body specialInfo">
                        <a href="#" class="thumbnail specialInfo">
                             <img  src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            <div class="col-lg-3 col-xs-12 col-sm-6  col-md-4 ">
                <!-- Default box -->
                <div class="box box-warning">
                    <div class="box-header specialInfo">
                        <h3 class="box-title" style="color: #2d5be3; font-weight: bold; line-height: 21px;"> Admin, Inc.</h3>
                        <div class="box-tools pull-right">                            
                            <span class="venueScore bg-yellow"><span>9.0</span></span>    
                        </div>
                    </div>
                    <div style="padding-left: 10px ;line-height: 1.42857; background: none repeat scroll 0 0 #fff4d8;  color: #aeb4b6;">
                        <span class="tipText" data-fulltext="" style="max-height: 32px;">                    
                          Muelle Malecon Simon Bolivar Guayaquil
                        </span>
                        <strong><br>Telefono : 09784512369</strong>
                    </div>
                    <div class="box-body specialInfo">
                        <a href="#" class="thumbnail specialInfo">
                             <img  src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/lo_nuestro.jpg" alt="125x125"/>
                        </a>
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <a class="small-box-footer" href="#">
                            More info <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div><!-- /.box-footer-->
                </div><!-- /.box -->
            </div><!-- /.col -->
            
            
            
        </div><!-- /.row -->

      
</section>

