
<!-- Header contenido (Encabezado de página) -->
<section class="content-header">
    <h1>
        Empresas o negocios
        <small id="subtitle_header">Tiendas</small>
    </h1>
</section>


<!-- Contenido principal -->
<section id="main_content" class="content">
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
        <div class="panel panel-default">
            <div class="row padall">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <span></span>
                    <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/avatar2.png" alt=""/>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                    <div class="clearfix">
                        <div class="pull-left">
                             <span class="icon">Negocio 1 nombre</span>
                        </div>
                        <div class="pull-right">
                             <b>Articulos:</b> 141 | <b>Ofertas:</b> 3 
                        </div>
                    </div>
                    <div>
                        <h4><span class="fa fa-map-marker icon"></span> Guasmo sur coop  18 oct max m sl 3</h4>
                        <b>Tlf:</b> 0978451278.
                        <span class="fa fa-search icon pull-right"> 
                            <a href="<?php echo $this->url('user', array('action'=>'detalles'));?>" >Ver mas</a>                            
                        </span>
                    </div>
                </div>
            </div>
            <div class="row padbig">
                <div id="map1" class="map" >
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
        <div class="panel panel-primary">
            <div class="row padall">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <span></span>
                    <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/avatar3.png" alt=""/>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                    <div class="clearfix">
                        <div class="pull-left">
                            <span class="fa fa-dollar icon">675, 000</span>
                        </div>
                        <div class="pull-right">
                            1,196 SqFt | 3 Bedrooms | 1 Bathroom                                
                        </div>
                    </div>
                    <div>
                        <h4><span class="fa fa-map-marker icon"></span>5108 24th St N</h4>
                        Build 2011. Fully Furnished.<span class="fa fa-search icon pull-right">   
                        <a href="#" onclick="loadMain(event , 'pages/det-ranqueo.php','Detalles Propietario');">Ver mas</a>                                
                        </span>
                    </div>
                </div>
            </div>
            <div class="row padbig">
                <div id="map2" class="map">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
        <div class="panel panel-primary">
            <div class="row padall">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <span></span>
                    <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/avatar5.png" alt=""/>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                    <div class="clearfix">
                        <div class="pull-left">
                            <span class="fa fa-dollar icon">$385,000</span>
                        </div>
                        <div class="pull-right">
                            1,135 SqFt | 2 Bedrooms | 2 Bathrooms                                
                        </div>
                    </div>
                    <div>
                        <h4><span class="fa fa-map-marker icon"></span>4195 S Four Mile Run Dr</h4>
                        Build 2001. Fully refurbished.<span class="fa fa-search icon pull-right">   Ver mas</span>
                    </div>
                </div>
            </div>
            <div class="row padbig">
                <div id="map3" class="map">
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
        <div class="panel panel-primary">
            <div class="row padall">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <span></span>
                    <img src="<?php echo $this->basePath(); ?>/AdminLTE-master/img/avatar04.png" alt=""/>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                    <div class="clearfix">
                        <div class="pull-left">
                            <span class="fa fa-dollar icon">945,000</span>
                        </div>
                        <div class="pull-right">
                            3,500 SqFt | 5 Bedrooms | 3 Bathrooms  
                        </div>
                    </div>
                    <div>
                        <h4><span class="fa fa-map-marker icon"></span>2717 S Arlington Ridge Rd</h4>
                        Build 2012. Call for availability.<span class="fa fa-search icon pull-right">  Ver mas</span>
                    </div>
                </div>
            </div>
            <div class="row padbig">
                <div id="map4" class="map">
                </div>
            </div>
        </div>
    </div>
</div>
</section>



<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false"></script>
<script type="text/javascript">
    jQuery(function ($) {
        function init_map1() {
            var myLocation = new google.maps.LatLng(51.508742,-0.120850);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map1"),
                mapOptions);
            marker.setMap(map);
        }
        function init_map2() {
            var myLocation = new google.maps.LatLng(38.898537, -77.13208299999997);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map2"),
                mapOptions);
            marker.setMap(map);
        }
        function init_map3() {
            var myLocation = new google.maps.LatLng(38.8507126, -77.09903600000001);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map3"),
                mapOptions);
            marker.setMap(map);
        }
        function init_map4() {
            var myLocation = new google.maps.LatLng(38.84753, -77.06577290000001);
            var mapOptions = {
                center: myLocation,
                zoom: 16
            };
            var marker = new google.maps.Marker({
                position: myLocation,
                title: "Property Location"
            });
            var map = new google.maps.Map(document.getElementById("map4"),
                mapOptions);
            marker.setMap(map);
        }

        init_map1();
        init_map2();
        init_map3();
        init_map4();
    });
</script>

<style>
    .gmnoprint img {
        max-width: none; 
    }

    .map {
        min-width: 300px;
        min-height:200px;
        width:100%;
    }

    img {
        max-width: 110%;
        height: auto;
    }

    .clearfix {
        clear: both;
    }

    .rowcolor {
        background-color: #CCCCCC;
    }

    .padall {
        padding: 10px;
    }

    .padbig {
        padding: 20px;
    }

    .icon {
        font-size: 23px;
        color: #197BB5;
    }
</style>